// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxhicTQklw3fAhiTxWruRdAC4JMWQtqtk',
    appId: '1:564821188747:web:2b32732346af33f929348e',
    messagingSenderId: '564821188747',
    projectId: 'whats-ym',
    authDomain: 'whats-ym.firebaseapp.com',
    storageBucket: 'whats-ym.firebasestorage.app',
    measurementId: 'G-3265M0KG7D',
    databaseURL: 'https://whats-ym-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQivbNipEd9bw-jyNrnd6pOCWnIRpPj9s',
    appId: '1:564821188747:android:dfb502ad3da57bae29348e',
    messagingSenderId: '564821188747',
    projectId: 'whats-ym',
    storageBucket: 'whats-ym.firebasestorage.app',
    databaseURL: 'https://whats-ym-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTv7ZZ5V8iwBpljuZeyMJeSR_pC7YIueo',
    appId: '1:564821188747:ios:dadf154f45a07fa129348e',
    messagingSenderId: '564821188747',
    projectId: 'whats-ym',
    storageBucket: 'whats-ym.firebasestorage.app',
    iosBundleId: 'com.example.whatsYourMood',
    databaseURL: 'https://whats-ym-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTv7ZZ5V8iwBpljuZeyMJeSR_pC7YIueo',
    appId: '1:564821188747:ios:dadf154f45a07fa129348e',
    messagingSenderId: '564821188747',
    projectId: 'whats-ym',
    storageBucket: 'whats-ym.firebasestorage.app',
    iosBundleId: 'com.example.whatsYourMood',
    databaseURL: 'https://whats-ym-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxhicTQklw3fAhiTxWruRdAC4JMWQtqtk',
    appId: '1:564821188747:web:464e616b0f029eec29348e',
    messagingSenderId: '564821188747',
    projectId: 'whats-ym',
    authDomain: 'whats-ym.firebaseapp.com',
    storageBucket: 'whats-ym.firebasestorage.app',
    measurementId: 'G-MH6NJS8M3K',
    databaseURL: 'https://whats-ym-default-rtdb.firebaseio.com',
  );
}
